@startuml

!theme plain
top to bottom direction
skinparam linetype ortho

class AddElementCommand {
  + AddElementCommand():
  + createNoAddNew(Scanner, boolean): HumanBeing
  + bodyOfCommand(String): void
  + createNoAddNewScanner(Scanner): HumanBeing
}
class AddIfMinCommand {
  + AddIfMinCommand():
  + bodyOfCommand(String): void
}
class Car {
  + Car(String, boolean):
  + Car(boolean, Scanner):
  + Car(boolean):
  + Car():
  - name: String
  - cool: boolean
  + toString(): String
   cool: boolean
   name: String
}
class ClearCommand {
  + ClearCommand():
  + bodyOfCommand(String): void
}
class CollectionManager {
  + CollectionManager():
  ~ timeOfCreation: String
  ~ initialazed: LocalDateTime
  + collection: ArrayList<HumanBeing>
  + addIfMin(HumanBeing): void
  + clear(): void
  + exit(): void
  + add(HumanBeing): void
  + minBySoundtrackName(): void
  + executeScriptFromFilename(String): void
  + removeFirst(): void
  + countGreaterThanMood(Mood): int
  + findMin(): HumanBeing
  + saveToFile(String): void
  + readEnv(): void
  + sort(): void
  + removeAnyByMood(Mood): void
  + removeById(int): void
  + updateID(int, HumanBeing): void
  + info(): void
  + readJson(String): void
   timeOfCreation: String
   collection: ArrayList<HumanBeing>
   initialazed: LocalDateTime
}
class Command {
  + Command():
  # description: String
  # nameOfCommand: String
  + description(): void
  + execute(String): void
  + bodyOfCommand(String): void
   nameOfCommand: String
   description: String
}
interface Commander << interface >> {
  + execute(String): void
  + execute(): void
  + description(): void
}
class ConsoleManager {
  + ConsoleManager():
  + startConsole(): void
}
class Coordinates {
  + Coordinates(boolean):
  + Coordinates(long, long):
  + Coordinates():
  + Coordinates(boolean, Scanner):
  - x: long
  - y: long
  + toString(): String
   y: long
   x: long
}
class CountGreaterThanMoodCommand {
  + CountGreaterThanMoodCommand():
  + bodyOfCommand(String): void
}
class ExecuteScriptFromFileCommand {
  + ExecuteScriptFromFileCommand():
  + bodyOfCommand(String): void
}
class ExitCommand {
  + ExitCommand():
  + bodyOfCommand(String): void
}
class HelpCommand {
  + HelpCommand():
  + bodyOfCommand(String): void
}
class HumanBeing {
  + HumanBeing(String, Coordinates, boolean, boolean, Long, String, WeaponType, Mood, Car):
  + HumanBeing(int, String, Coordinates, Date, boolean, boolean, Long, String, WeaponType, Mood, Car):
  + HumanBeing():
  + HumanBeing(boolean):
  - id: int
  - hasToothpick: boolean
  - impactSpeed: Long
  - realHero: boolean
  - soundtrackName: String
  - mood: Mood
  - coordinates: Coordinates
  - weaponType: WeaponType
  - car: Car
  - creationDate: Date
  - name: String
  + compareTo(HumanBeing): int
  + toString(): String
   name: String
   coordinates: Coordinates
   hasToothpick: boolean
   soundtrackName: String
   mood: Mood
   impactSpeed: Long
   creationDate: Date
   realHero: boolean
   weaponType: WeaponType
   id: int
   car: Car
}
class IDGen {
  + IDGen():
  + gen(): int
}
class IllegalScriptLine {
  + IllegalScriptLine(String):
  ~ message: String
   message: String
}
class IncorrectArgsNumber {
  + IncorrectArgsNumber(int):
   message: String
}
class InfoCommand {
  + InfoCommand():
  + bodyOfCommand(String): void
}
class InputFieldBuilder<T> {
  - InputFieldBuilder(Scanner, Class<T>):
  + build(Scanner, Class<T>): InputFieldBuilder<T>
  + againMsgParams(String): InputFieldBuilder<T>
  + start(String): InputFieldBuilder<T>
  + inputParams(String): InputFieldBuilder<T>
  + againMsg(String): InputFieldBuilder<T>
  + end(String): InputFieldBuilder<T>
  + build(): T
}
class Invoker {
  + Invoker():
  + adder(): void
}
class JsonParser {
  + JsonParser():
  + collectionToJson(String, ArrayList<HumanBeing>): void
  + jsonToCollection(String): ArrayList<HumanBeing>?
}
class Main {
  + Main():
  + main(String[]): void
}
class MinBySoundtrackNameCommand {
  + MinBySoundtrackNameCommand():
  + bodyOfCommand(String): void
}
enum Mood << enumeration >> {
  - Mood(int):
  - pointOfHappy: int
  + valueOf(String): Mood
  + values(): Mood[]
   v: String
   pointOfHappy: int
}
class MoodComparator {
  + MoodComparator():
  + compare(HumanBeing, HumanBeing): int
}
class NullCoordinatesException {
  + NullCoordinatesException():
   message: String
}
class NullStringException {
  + NullStringException():
   message: String
}
class ReadCommand {
  + ReadCommand():
  + bodyOfCommand(String): void
}
class ReadEnvCommand {
  + ReadEnvCommand():
  + bodyOfCommand(String): void
}
class RemoveAnyByMoodCommand {
  + RemoveAnyByMoodCommand():
  + bodyOfCommand(String): void
}
class RemoveByIDCommand {
  + RemoveByIDCommand():
  + bodyOfCommand(String): void
}
class RemoveFirstCommand {
  + RemoveFirstCommand():
  + bodyOfCommand(String): void
}
class SaveToFileCommand {
  + SaveToFileCommand():
  + bodyOfCommand(String): void
}
class ScriptFileReader {
  + ScriptFileReader():
  + readFile(String): void
}
class ShowCommand {
  + ShowCommand():
  + bodyOfCommand(String): void
}
class SortCommand {
  + SortCommand():
  + bodyOfCommand(String): void
}
class SoundtrackNameComparator {
  + SoundtrackNameComparator():
  + compare(HumanBeing, HumanBeing): int
}
class TypeOfClassMap {
  + TypeOfClassMap():
}
class UpdateIDCommand {
  + UpdateIDCommand():
  + bodyOfCommand(String): void
}
enum WeaponType << enumeration >> {
  - WeaponType(int):
  - degreeOfCool: int
  + values(): WeaponType[]
  + valueOf(String): WeaponType
   degreeOfCool: int
   v: String
}
class WrongAddLineInScriptException {
  + WrongAddLineInScriptException():
   message: String
}
class WrongNameHumanBeingException {
  + WrongNameHumanBeingException():
   message: String
}
class WrongNameSizeException {
  + WrongNameSizeException():
   message: String
}

AddElementCommand              -[#595959,dashed]->  Car                           : "«create»"
AddElementCommand              -[#000082,plain]-^  Command
AddElementCommand              -[#595959,dashed]->  Coordinates                   : "«create»"
AddElementCommand              -[#595959,dashed]->  HumanBeing                    : "«create»"
AddElementCommand              -[#595959,dashed]->  IllegalScriptLine             : "«create»"
AddIfMinCommand                -[#595959,dashed]->  AddElementCommand             : "«create»"
AddIfMinCommand                -[#000082,plain]-^  Command
Car                            -[#595959,dashed]->  NullStringException           : "«create»"
Car                            -[#595959,dashed]->  WrongAddLineInScriptException : "«create»"
ClearCommand                   -[#000082,plain]-^  Command
CollectionManager             "1" *-[#595959,plain]-> "collection\n*" HumanBeing
CollectionManager              -[#595959,dashed]->  MoodComparator                : "«create»"
CollectionManager              -[#595959,dashed]->  NullStringException           : "«create»"
CollectionManager              -[#595959,dashed]->  ScriptFileReader              : "«create»"
CollectionManager              -[#595959,dashed]->  SoundtrackNameComparator      : "«create»"
Command                       "1" *-[#595959,plain]-> "cm\n1" CollectionManager
Command                        -[#595959,dashed]->  IncorrectArgsNumber           : "«create»"
ConsoleManager                "1" *-[#595959,plain]-> "cm\n1" CollectionManager
ConsoleManager                 -[#595959,dashed]->  IncorrectArgsNumber           : "«create»"
ConsoleManager                "1" *-[#595959,plain]-> "inv\n1" Invoker
CountGreaterThanMoodCommand    -[#000082,plain]-^  Command
ExecuteScriptFromFileCommand   -[#000082,plain]-^  Command
ExitCommand                    -[#000082,plain]-^  Command
HelpCommand                    -[#000082,plain]-^  Command
HumanBeing                    "1" *-[#595959,plain]-> "car\n1" Car
HumanBeing                    "1" *-[#595959,plain]-> "coordinates\n1" Coordinates
HumanBeing                    "1" *-[#595959,plain]-> "mood\n1" Mood
HumanBeing                    "1" *-[#595959,plain]-> "weaponType\n1" WeaponType
InfoCommand                    -[#000082,plain]-^  Command
InputFieldBuilder              -[#595959,dashed]->  NullStringException           : "«create»"
Invoker                        -[#595959,dashed]->  AddElementCommand             : "«create»"
Invoker                        -[#595959,dashed]->  AddIfMinCommand               : "«create»"
Invoker                        -[#595959,dashed]->  ClearCommand                  : "«create»"
Invoker                       "1" *-[#595959,plain]-> "commands\n*" Command
Invoker                        -[#595959,dashed]->  CountGreaterThanMoodCommand   : "«create»"
Invoker                        -[#595959,dashed]->  ExecuteScriptFromFileCommand  : "«create»"
Invoker                        -[#595959,dashed]->  ExitCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  HelpCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  InfoCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  MinBySoundtrackNameCommand    : "«create»"
Invoker                        -[#595959,dashed]->  ReadCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  ReadEnvCommand                : "«create»"
Invoker                        -[#595959,dashed]->  RemoveAnyByMoodCommand        : "«create»"
Invoker                        -[#595959,dashed]->  RemoveByIDCommand             : "«create»"
Invoker                        -[#595959,dashed]->  RemoveFirstCommand            : "«create»"
Invoker                        -[#595959,dashed]->  SaveToFileCommand             : "«create»"
Invoker                        -[#595959,dashed]->  ShowCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  SortCommand                   : "«create»"
Invoker                        -[#595959,dashed]->  UpdateIDCommand               : "«create»"
Main                          "1" *-[#595959,plain]-> "cm\n1" CollectionManager
Main                           -[#595959,dashed]->  CollectionManager             : "«create»"
Main                           -[#595959,dashed]->  ConsoleManager                : "«create»"
Main                           -[#595959,dashed]->  Invoker                       : "«create»"
Main                          "1" *-[#595959,plain]-> "inv\n1" Invoker
MinBySoundtrackNameCommand     -[#000082,plain]-^  Command
ReadCommand                    -[#000082,plain]-^  Command
ReadEnvCommand                 -[#000082,plain]-^  Command
RemoveAnyByMoodCommand         -[#000082,plain]-^  Command
RemoveByIDCommand              -[#000082,plain]-^  Command
RemoveFirstCommand             -[#000082,plain]-^  Command
SaveToFileCommand              -[#000082,plain]-^  Command
ScriptFileReader               -[#595959,dashed]->  AddElementCommand             : "«create»"
ScriptFileReader               -[#595959,dashed]->  IllegalScriptLine             : "«create»"
ShowCommand                    -[#000082,plain]-^  Command
SortCommand                    -[#000082,plain]-^  Command
UpdateIDCommand                -[#595959,dashed]->  AddElementCommand             : "«create»"
UpdateIDCommand                -[#000082,plain]-^  Command
@enduml
